apiVersion: v1
kind: Service
metadata:
  name: color-service
spec:
  type: NodePort
  selector:
    app: color-service
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-service
spec:
  replicas: 8
  selector:
    matchLabels:
      app: color-service
  template:
    metadata:
      labels:
        app: color-service
    spec:
      containers:
        - name: color-service
          image: k3d-local:12345/color-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
